# docker-compose.yml
services:
  # mysql
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todoapp
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - app-net

  # flyway
  flyway:
    build:
      context: ./docker/flyway
      dockerfile: Dockerfile
    volumes:
      - ./docker/flyway/db:/flyway/db
      - ./docker/flyway/sql:/flyway/sql
      - ./docker/flyway/conf:/flyway/conf
    depends_on:
      db:
        condition: service_healthy
    command: -connectRetries=60 migrate
    networks:
      - app-net
  nginx:
    image: nginx:latest
    container_name: todo_nginx
    ports:
      - "443:443"
    volumes:
      # React ビルド成果物を Nginx の公開ディレクトリにマウント
      - ./front/dist:/usr/share/nginx/html

      # Nginx 設定ファイ
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

      # SSL 証明書
      - ./docker/nginx/certs/localhost.crt:/etc/ssl/certs/nginx.crt
      - ./docker/nginx/certs/localhost.key:/etc/ssl/private/nginx.key
    restart: unless-stopped
    depends_on:
      bff-server:
        condition: service_started # BFFのコンテナが起動するのを待
      front-server:
        condition: service_started
    networks:
      - app-net
  resource-server:
    container_name: resource-server
    build:
      context: ./servlet/resource
      dockerfile: Dockerfile
    depends_on:
      flyway:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/todoapp
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret
    networks:
      - app-net

  bff-server:
    container_name: bff-server
    build:
      context: ./servlet/bff
      dockerfile: Dockerfile
    depends_on:
      flyway:
        condition: service_completed_successfully
    ports:
      - "7070:7070"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/todoapp
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret

    networks:
      - app-net

  front-server:
    image: node:20
    working_dir: /app
    command: sh -c "npm ci && npm run dev -- --host"
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - app-net
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

volumes:
  mysql_data:


networks:
  app-net:
    driver: bridge
