spring:
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: never
    google:
      genai:
        api-key: ${SPRING_AI_GOOGLE_GENAI_API_KEY}
        project-id: ${SPRING_AI_GOOGLE_GENAI_PROJECT_ID}
        chat:
          options:
            include-thoughts: true
  application:
    name: app1
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db:3306/todoapp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Tokyo

  jpa:
    hibernate:
      ddl-auto: validate
      
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: false

server:
  port: ${PORT:8080}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-1jp2ogye74qnxdfh.jp.auth0.com/
       

logging:
  level:
    root: INFO
    com.example.app1.controller: INFO
    com.example.app1.service: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    com.example.app1: INFO
  file:
    name: /home/takumi/todo-app/backend/logs/app1.log


app:
  base-url: ${APP_BASE_URL:https://localhost}
  bff-server-url: ${APP_BFF_SERVER_URL:https://localhost:8081}
  security:
    jwk:
      private-key: 
      public-key:
      key-id:
# com:
#   group:
#     project:
#       jwt:
#         secret: X/ssIXQSQI1RVHLN1AZ8AcK4EkB0oJSEYwZK1K//okAaCFI9SZZ0UzeHNmVAbJeLVbFkzJdBtBI4A+TkzPe+7w==
#         issuer: ${OAUTH2_ISSUER_URI:http://localhost:8080}
#         expires: 900
#       cookie:
#         name: accessToken
#         expires: 86400
