spring:
  application:
    name: app1
  datasource:
    url: jdbc:mysql://db:3306/todoapp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
    locations: classpath:db/migration

logging:
  level:
    root: ERROR
    com.service.AuthService: DEBUG
    com.controller.AuthController: DEBUG
    com.utils.JwtUtils: DEBUG
    com.utils.JwtConfig: INFOd

  file:
    name: /app/logs/app1.log
  logback:
    rollingpolicy:
      file-name-pattern: /app/logs/app1.%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB


com:
  group:
    project:
      jwt:
        secret: ++36xfSobeiERWDtfXGvtF1MTkxHITOKR0R8j/8OsTs=
        issuer: ${OAUTH2_ISSUER_URI:http://localhost:8080}
        expires: 900
      cookie:
        name: accessToken
        expires: 86400
