spring:
  application:
    name: app1
  datasource:
    url: jdbc:mysql://db:3306/todoapp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
    locations: classpath:db/migration

logging:
  level:
    org.springframework.security: TRACE
    com.example.app1: DEBUG
  file:
    name: /home/takumi/todo-app/backend/logs/app1.log


com:
  group:
    project:
      jwt:
        secret: X/ssIXQSQI1RVHLN1AZ8AcK4EkB0oJSEYwZK1K//okAaCFI9SZZ0UzeHNmVAbJeLVbFkzJdBtBI4A+TkzPe+7w==
        issuer: ${OAUTH2_ISSUER_URI:http://localhost:8080}
        expires: 900
      cookie:
        name: accessToken
        expires: 86400
