spring:
  datasource:
    url: jdbc:mysql://db:3306/todoapp
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: false
    locations: classpath:db/migration

com:
  group:
    project:
      jwt:
        secret: my-super-secret-key-takumi-yonenaka-2005-0606
        issuer: ${OAUTH2_ISSUER_URI:http://localhost:8080}
        expires: 900
      cookie:
        name: MYCOOKIE
        expires: 86400
